- hosts: localhost
  gather_facts: true
  roles:
    - role: ssh
      tags: ssh

    - role: inventory
      tags:
        - inventory
        # - never  # 手動で hosts を作成する場合は never タグを付ける

- hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  remote_user: ansible_user
  roles:
    - role: user
      tags: user
