- name: Allow PermitRootLogin
  copy:
    content: |
      PermitRootLogin yes
      PubkeyAuthentication yes
      PasswordAuthentication no
    dest: /etc/ssh/sshd_config.d/PermitRootLogin.conf
    force: yes

- name: Reload sshd
  systemd:
    name: sshd
    state: reloaded
  changed_when: false
