- name: Retrieve lvs result before taking snapshot
  command: lvs {{ vg_name }} -o lv_name,vg_name,attr,size,pool_lv,origin,data_percent,metadata_percent
  register: result_lvs

- name: Display lvs result before taking snapshot
  debug:
    var: result_lvs.stdout_lines

- name: Retrieve lvdisplay result before taking snapshot
  command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
  register: result_lvdisplay

- name: Display lvdisplay result before taking snapshot
  debug:
    var: result_lvdisplay.stdout_lines

- name: Create snapshot volume if not already present
  command: lvcreate -sl 100%ORIGIN -n {{ snapshot_name }} /dev/{{ vg_name }}/{{ lv_name }}
  when:
    - snapshot_name not in result_lvs.stdout
    - snapshot_name not in result_lvdisplay.stdout

- name: Retrieve lvdisplay result after taking snapshot
  command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
  register: result_lvdisplay

- name: Display lvdisplay result after taking snapshot
  debug:
    var: result_lvdisplay.stdout_lines

- name: Retrieve lvs result after taking snapshot
  command: lvs {{ vg_name }} -o lv_name,vg_name,attr,size,pool_lv,origin,data_percent,metadata_percent
  register: result_lvs

- name: Display lvs result after taking snapshot
  debug:
    var: result_lvs.stdout_lines
