- name: Retrieve lvdisplay result before merging snapshot
  command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
  register: result_lvdisplay

- name: Display lvdisplay result before merging snapshot
  debug:
    var: result_lvdisplay.stdout_lines

- name: Merge existing snapshot into original logical volume
  command: lvconvert --merge /dev/{{ vg_name }}/{{ snapshot_name }}
  when: snapshot_name in result_lvdisplay.stdout

- name: Reboot system to activate merge
  reboot:
    reboot_timeout: 300

- name: Activate original logical volume after reboot
  command: lvchange -ay /dev/{{ vg_name }}/{{ lv_name }}

- name: Wait for snapshot to merge completely
  shell: lvdisplay /dev/{{ vg_name }}/{{ lv_name }} | grep {{ snapshot_name }}
  register: result_lvdisplay_grep
  failed_when: false
  until: result_lvdisplay_grep.rc != 0
  retries: 360
  delay: 10

- name: Retrieve lvdisplay result after merging snapshot
  command: lvdisplay /dev/{{ vg_name }}/{{ lv_name }}
  register: result_lvdisplay

- name: Display lvdisplay result after merging snapshot
  debug:
    var: result_lvdisplay.stdout_lines
